prefix SDGIO: <http://purl.unep.org/sdg/SDGIO_>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?subjectClass ?subectClassLabel ?relationship ?relationshipLabel ?objectClass ?objectClassLabel
WHERE {
  {?subjectClass rdfs:subClassOf [
    a owl:Restriction ;
    owl:onProperty ?relationship ;
    owl:someValuesFrom ?objectClass
  ] 
  }
  UNION {
   ?subjectClass rdfs:subClassOf ?objectClass .
   BIND(rdfs:subClassOf AS ?relationship)
  }
  ?subjectClass rdfs:label ?subjectClassLabel .
  ?objectClass rdfs:label ?objectClassLabel .
  OPTIONAL { ?relationship rdfs:label ?relationshipLabel }
}
